# Jekyll Resume Theme

# Site settings
title: Carlos' Resume 
email: carlosfilho92@gmail.com
description: Just my resume 
baseurl: '/resume'
author: 'Carlos Filho'
url: 'crlsfilho.github.io/resume'

name: Carlos Filho
job: digital marketer

# Build settings
markdown: kramdown
