# Jekyll Resume Theme

# Site settings
title: Carlos' Resume 
email: carlos@carlosfilho.co
description: This is just my resume made in Jekyll
baseurl: "/resume"
url: "http://mattcouchman.co.uk/jekyll-resume"
name: Carlos Filho 
job: digital marketer 
location: Curitiba, BR
languages: HTML, CSS and Javascript
twitter_username: crlsfilho 
github_username:  crlsfilho
email_address: carlos@carlosfilho.co

# Build settings
markdown: kramdown
